#!/bin/sh /etc/rc.common

START=80
STOP=20

USE_PROCD=1

reload_service()
{
    ubus call ipsec reload
}

start_service()
{
    procd_open_instance
    procd_set_param command /sbin/vpnd
    procd_set_param respawn
    procd_close_instance
}


